# See the Conductor setup guide at https://packagist.com/docs/conductor/getting-started

on:
    repository_dispatch:
        types:
            - dependency_update

name: Private Packagist Conductor

permissions:
    contents: write

jobs:
    conductor:
        name: Private Packagist Conductor
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            # Install PHP. You can also replace this step by
            # reusing an existing workflow that sets up PHP.
            # Additional services required to run composer
            # install/update, such as Node.js or a database,
            # must be set up here too.
            - name: Install PHP
              uses: shivammathur/setup-php@0f7f1d08e3e32076e51cae65eb0b0c871405b16e # 2.34.1
              with:
                  php-version: "latest"
                  coverage: "none"

            # See the Conductor GitHub Action at https://github.com/packagist/conductor-github-action
            - name: "Running Conductor"
              uses: packagist/conductor-github-action@v1
